<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-06 10:39
=======
# Generated by Django 5.2 on 2025-05-19 10:12
>>>>>>> 6b18fb2 (model apres modification de authentification)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('commentaires', models.TextField()),
                ('status', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('profilsante', models.CharField(max_length=100)),
=======
                ('profilsante', models.FileField(blank=True, null=True, upload_to='profils_sante/')),
>>>>>>> 6b18fb2 (model apres modification de authentification)
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programme.programmesportif')),
            ],
        ),
    ]
