# Generated by Django 5.2 on 2025-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='profilsante',
            field=models.FileField(blank=True, null=True, upload_to='profils_sante/'),
        ),
    ]
