# Generated by Django 5.2 on 2025-05-20 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin_global', 'Admin Global'), ('admin_entreprise', 'Admin Entreprise'), ('coach', 'Coach'), ('employe', 'Employé')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='utilisateur_set', related_query_name='utilisateur', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='utilisateur_set', related_query_name='utilisateur', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Utilisateur Global',
                'verbose_name_plural': 'Utilisateurs Globaux',
            },
        ),
        migrations.CreateModel(
            name='AdminEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_entreprise', to='entreprise.entreprise')),
                ('user_id', models.OneToOneField(limit_choices_to={'role': 'admin_entreprise'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_entreprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(limit_choices_to={'role': 'admin_global'}, on_delete=django.db.models.deletion.CASCADE, related_name='Admin_global_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('experience', models.TextField()),
                ('specialites', models.TextField(blank=True)),
                ('user_id', models.OneToOneField(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_embauche', models.DateField()),
                ('date_naissance', models.DateField()),
                ('poste', models.CharField(max_length=100)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='accounts.coach')),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='entreprise.entreprise')),
                ('user_id', models.OneToOneField(limit_choices_to={'role': 'employe'}, on_delete=django.db.models.deletion.CASCADE, related_name='employe_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilsante', models.FileField(blank=True, null=True, upload_to='profils_sante/')),
                ('employer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_sante', to='accounts.employer')),
            ],
        ),
    ]
