<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-06 10:39

import django.db.models.deletion
=======
# Generated by Django 5.2 on 2025-05-19 10:12

import django.db.models.deletion
from django.conf import settings
>>>>>>> 6b18fb2 (model apres modification de authentification)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('auth', '0012_alter_user_first_name_max_length'),
>>>>>>> 6b18fb2 (model apres modification de authentification)
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='AdminEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('competences', models.TextField(blank=True)),
                ('poste', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('dateEmbauche', models.DateField()),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise')),
            ],
            options={
                'abstract': False,
            },
=======
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin_global', 'Admin Global'), ('admin_entreprise', 'Admin Entreprise'), ('coach', 'Coach'), ('employe', 'Employé')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='utilisateur_set', related_query_name='utilisateur', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='utilisateur_set', related_query_name='utilisateur', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Utilisateur Global',
                'verbose_name_plural': 'Utilisateurs Globaux',
            },
        ),
        migrations.CreateModel(
            name='AdminEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('date_embauche', models.DateField()),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_entreprise', to='entreprise.entreprise')),
                ('user_id', models.OneToOneField(limit_choices_to={'role': 'admin_entreprise'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_entreprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
>>>>>>> 6b18fb2 (model apres modification de authentification)
        ),
        migrations.CreateModel(
            name='AdminGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('competences', models.TextField(blank=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise')),
            ],
            options={
                'abstract': False,
            },
=======
                ('competences', models.TextField(blank=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Admin_global_profile', to=settings.AUTH_USER_MODEL)),
            ],
>>>>>>> 6b18fb2 (model apres modification de authentification)
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('competences', models.TextField(blank=True)),
                ('certification', models.TextField()),
                ('experience', models.TextField()),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise')),
            ],
            options={
                'abstract': False,
            },
=======
                ('certification', models.TextField()),
                ('experience', models.TextField()),
                ('specialites', models.TextField(blank=True)),
                ('user_id', models.OneToOneField(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
>>>>>>> 6b18fb2 (model apres modification de authentification)
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('competences', models.TextField(blank=True)),
                ('dateEmbauche', models.DateField()),
                ('dateNaissance', models.DateField()),
                ('poste', models.CharField(max_length=100)),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise')),
            ],
            options={
                'abstract': False,
            },
=======
                ('date_embauche', models.DateField()),
                ('date_naissance', models.DateField()),
                ('poste', models.CharField(max_length=100)),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='entreprise.entreprise')),
                ('user_id', models.OneToOneField(limit_choices_to={'role': 'employe'}, on_delete=django.db.models.deletion.CASCADE, related_name='employe_profile', to=settings.AUTH_USER_MODEL)),
            ],
>>>>>>> 6b18fb2 (model apres modification de authentification)
        ),
    ]
