# Generated by Django 5.2 on 2025-05-20 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilsante',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='profilsante',
            name='profilsante',
        ),
        migrations.AddField(
            model_name='profilsante',
            name='date_creation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='profilsante',
            name='fichier_profil',
            field=models.FileField(default=1, upload_to='profils_sante/'),
            preserve_default=False,
        ),
    ]
