# Generated by Django 5.2 on 2025-05-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminentreprise',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='certification',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
