# Generated by Django 5.2 on 2025-05-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminglobal',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='entreprise',
        ),
    ]
