# Generated by Django 5.2.1 on 2025-05-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur Global', 'verbose_name_plural': 'Utilisateurs Globaux'},
        ),
    ]
