# Generated by Django 5.2.1 on 2025-05-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_utilisateur_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminglobal',
            name='competences',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
