# Generated by Django 5.2 on 2025-05-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profilsante_employer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilSante',
        ),
    ]
