# Generated by Django 5.2.1 on 2025-05-19 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_adminglobal_competences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='accounts.coach'),
        ),
        migrations.AlterField(
            model_name='adminentreprise',
            name='user_id',
            field=models.OneToOneField(limit_choices_to={'role': 'admin_entreprise'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_entreprise_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminglobal',
            name='user_id',
            field=models.OneToOneField(limit_choices_to={'role': 'admin_global'}, on_delete=django.db.models.deletion.CASCADE, related_name='Admin_global_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user_id',
            field=models.OneToOneField(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user_id',
            field=models.OneToOneField(limit_choices_to={'role': 'employe'}, on_delete=django.db.models.deletion.CASCADE, related_name='employe_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
