<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-06 10:39
=======
# Generated by Django 5.2 on 2025-05-19 10:12
>>>>>>> 6b18fb2 (model apres modification de authentification)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeSportif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('objectif', models.TextField()),
                ('description', models.TextField()),
<<<<<<< HEAD
                ('duree', models.DateField()),
=======
                ('duree', models.DateTimeField()),
>>>>>>> 6b18fb2 (model apres modification de authentification)
                ('frequence', models.CharField(max_length=100)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.coach')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer')),
            ],
        ),
    ]
