# Generated by Django 5.2 on 2025-05-20 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_sente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_goal', models.CharField(choices=[('weight_loss', 'Perte de poids'), ('muscle_gain', 'Renforcement musculaire'), ('cardio', 'Amélioration cardio'), ('competition', 'Préparation à une compétition'), ('other', 'Autre')], max_length=50, verbose_name='Objectif sportif')),
                ('current_activity_level', models.CharField(max_length=50, verbose_name="Niveau d'activité actuel")),
                ('desired_frequency', models.PositiveIntegerField(verbose_name='Séances/semaine souhaitées')),
                ('recent_injuries', models.TextField(blank=True, null=True, verbose_name='Blessures récentes')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='Maladies chroniques')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Poids (kg)')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Taille (cm)')),
                ('recommended_activities', models.TextField(blank=True, null=True, verbose_name='Activités conseillées')),
                ('limitations', models.TextField(blank=True, null=True, verbose_name='Limites à respecter')),
                ('needs_coaching', models.BooleanField(default=False, verbose_name="Besoin d'un encadrement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'employe'}, on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile_sente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
