# Generated by Django 5.2 on 2025-05-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_sente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_sente',
            name='desired_frequency',
        ),
    ]
