# Generated by Django 5.2 on 2025-05-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_sente', '0002_remove_profile_sente_desired_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_sente',
            name='limitations',
        ),
    ]
